### ISSUE TITLE
Update Github workflow script to get info about recently executed functions in smal file

### ISSUE THREAD

**Issue by qarmin** [goostengine/goost-fuzzer#1]
As can be see here - https://github.com/qarmin/Qarminer/actions/runs/1249293607

there are now an artifacts to download, which are produced after each run(even unsuccessful), which provide small file(max 10-20MB, but usually few MB) with info about executed functions with parameters in last run e.g.
```
######################################## _OS ########################################
	var temp_variable = ClassDB.instance("_OS")
	temp_variable.is_keep_screen_on()
	temp_variable.is_vsync_enabled()
	temp_variable.set_vsync_via_compositor(false)
	temp_variable.set_window_position(Vector2(0.90613, 0.423))
	temp_variable.can_draw()
	temp_variable.set_thread_name(".")
	temp_variable.get_ime_selection()
	temp_variable.set_screen_orientation(-42)
	temp_variable.center_window()
```

This is how it looks workflow file 
https://github.com/qarmin/Qarminer/blob/0dba2d194f0644f32da32b429daa6739b369b7ae/.github/workflows/linux_builds_1.yml#L46-L60

**Comment by Xrayez** [comment]
Yeah, this should make it easier to reproduce bugs locally by simply copy-pasting the code, thanks!

In my case `result.txt` is much smaller because I only run fuzzer for 5 minutes (I've found it sufficient for the number of classes that are tested).

See https://github.com/goostengine/goost-fuzzer/runs/3644425916

Looks like there's a new bug revealed there as well... 😅 **Update**: fixed in https://github.com/goostengine/goost/commit/e9bfff141053c93432855b16f8bdef00dca76ff1.
